### ISSUE TITLE
Józef Zawieja - informacja z czasopisma Dzień Pomorski

### ISSUE THREAD

**Issue by virtum** [siudek-family/album-junger-family#48]
https://kpbc.umk.pl/Content/211767/Czasopisma_POPC_004_204_02_182_HD_009.pdf
(pdf słabo się renderuje w przeglądarce firefox, lepiej pobrać i otworzyć lokalnie w adobe)

Na stronie 8, w sekcji "Wyniki Zawodów Pływackich" (prawa część strony), punkt 2, jest wspomniany Józef Zawieja.

AC:
- zweryfikować czy wspomniany Józef Zawieja to ten z naszej rodziny
- zweryfikować podany stopień st. post. - to prawdopodobnie starszy posterunkowy i nie jest to stopień wojskowy

**Comment by siudeks** [comment]
Dzięki za linka
Tytuł to "Wielkie święto sportowe Policji Państwowej"
Czyli to nie nasz, bo w okresie międzywojennym Józef pracował w Sądzie w Ostrowie, nie w policji.
Do zamknięcia :) (najwyżej będzie reopen)
