### ISSUE TITLE
Józef Zawieja - informacja z Muzeum Miasta Ostrowa Wielkopolskiego 

### ISSUE THREAD

**Issue by virtum** [siudek-family/album-junger-family#49]
https://m.rc.fm/kulturalne/ostrow-wielkopolski-nowe-starocie-w-muzeum.html#

Na stronie znajduje się: "Inna ciekawostka to dzienniczek Józefa Zawiei z lat 1913-1914. To niezwykłe źródło historyczne, które urywa się w momencie powołania autora do wojska w okresie wybuchu I Wojny Światowej."

AC:
- [ ] skontaktować się z muzeum i pozyskać więcej informacji (skany?) o wspomnianym dzienniczku
- [ ] Sprawdzić czy mają coś jeszcze o Zawiejach (może obraz?)
- [ ] Zweryfikować czy to *nasz* Józef zawieja
- [ ] Dowiedzieć się historii jak ten dzienniczek znalazł się w zasobach Muzeum

**Comment by siudeks** [comment]
Brzmi mega, będę dzwonił

**Comment by siudeks** [comment]
Pominięte na tą chwilę, ponieważ nie wiemy czy pismo w pamiętniku jest takie samo jak w albumie
